import type { CVData, CodeLanguage } from './types';

const languages: CodeLanguage[] = ['csharp', 'python', 'typescript', 'go', 'rust', 'java'];

export const personas: CVData[] = [
  {
    personal: { firstName: 'Alex', lastName: 'Chen', title: 'Full Stack Developer', email: 'alex.chen@dev.io', phone: '+1 555 0142', location: 'San Francisco, CA', age: 28 },
    summary: 'Passionate full-stack developer with 6 years of experience building scalable web applications. Specialized in React, Node.js, and cloud architecture.',
    skills: { platforms: ['Linux', 'Docker', 'AWS', 'Vercel'], programmingLanguages: ['TypeScript', 'Python', 'Rust', 'Go'], software: ['VS Code', 'PostgreSQL', 'Redis', 'Git'] },
    education: [{ id: '1', school: 'Stanford University', degree: 'Master', field: 'Computer Science', startYear: 2018, endYear: 2020, description: 'Focus on distributed systems and machine learning.' }],
    experience: [{ id: '1', company: 'Vercel', role: 'Senior Frontend Engineer', startDate: '03/2022', endDate: null, description: 'Building next-gen web deployment tools. Leading a team of 5 engineers.', technologies: ['Next.js', 'TypeScript', 'React'] }, { id: '2', company: 'Stripe', role: 'Software Engineer', startDate: '06/2020', endDate: '02/2022', description: 'Developed payment APIs handling millions of transactions daily.', technologies: ['Ruby', 'Go', 'PostgreSQL'] }],
    languages: [{ name: 'English', level: 'Native' }, { name: 'Mandarin', level: 'Fluent' }],
    personality: ['Problem Solver', 'Team Player', 'Detail Oriented'],
    media: [{ platform: 'GitHub', url: 'github.com/alexchen' }, { platform: 'LinkedIn', url: 'linkedin.com/in/alexchen' }],
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    codeLanguage: 'csharp',
  },
  {
    personal: { firstName: 'Sara', lastName: 'Kowalski', title: 'Data Scientist', email: 'sara.k@ml.dev', phone: '+48 500 123 456', location: 'Warsaw, Poland', age: 31 },
    summary: 'Data scientist with expertise in NLP and computer vision. Published researcher with 4 papers in top-tier conferences.',
    skills: { platforms: ['AWS SageMaker', 'GCP', 'Jupyter', 'Docker'], programmingLanguages: ['Python', 'R', 'SQL', 'Julia'], software: ['PyTorch', 'TensorFlow', 'Pandas', 'Spark'] },
    education: [{ id: '1', school: 'University of Warsaw', degree: 'PhD', field: 'Machine Learning', startYear: 2016, endYear: 2020, description: 'Research on transformer architectures for NLP.' }],
    experience: [{ id: '1', company: 'DeepMind', role: 'Research Scientist', startDate: '01/2021', endDate: null, description: 'Working on large language models and reinforcement learning.', technologies: ['Python', 'JAX', 'TPU'] }, { id: '2', company: 'Allegro', role: 'ML Engineer', startDate: '09/2018', endDate: '12/2020', description: 'Built recommendation engine serving 20M users.', technologies: ['Python', 'Spark', 'Kafka'] }],
    languages: [{ name: 'Polish', level: 'Native' }, { name: 'English', level: 'Fluent' }],
    personality: ['Analytical', 'Curious', 'Methodical'],
    media: [{ platform: 'GitHub', url: 'github.com/sarakowalski' }, { platform: 'Scholar', url: 'scholar.google.com/sara' }],
    photo: 'https://randomuser.me/api/portraits/women/44.jpg',
    codeLanguage: 'python',
  },
  {
    personal: { firstName: 'Marcus', lastName: 'Johnson', title: 'DevOps Engineer', email: 'marcus@infra.io', phone: '+1 555 0198', location: 'Austin, TX', age: 34 },
    summary: 'Infrastructure specialist with 8 years of experience in cloud-native systems. Kubernetes certified and Terraform expert.',
    skills: { platforms: ['AWS', 'GCP', 'Kubernetes', 'Terraform'], programmingLanguages: ['Go', 'Python', 'Bash', 'HCL'], software: ['Prometheus', 'Grafana', 'ArgoCD', 'Vault'] },
    education: [{ id: '1', school: 'Georgia Tech', degree: 'Bachelor', field: 'Computer Engineering', startYear: 2008, endYear: 2012, description: 'Focus on networking and distributed systems.' }],
    experience: [{ id: '1', company: 'Datadog', role: 'Senior SRE', startDate: '05/2021', endDate: null, description: 'Managing infrastructure for observability platform at scale.', technologies: ['Go', 'Kubernetes', 'Terraform'] }, { id: '2', company: 'Netflix', role: 'DevOps Engineer', startDate: '03/2017', endDate: '04/2021', description: 'Built CI/CD pipelines for microservices architecture.', technologies: ['Java', 'Spinnaker', 'AWS'] }],
    languages: [{ name: 'English', level: 'Native' }],
    personality: ['Reliable', 'Systematic', 'Calm Under Pressure'],
    media: [{ platform: 'GitHub', url: 'github.com/marcusjohnson' }, { platform: 'LinkedIn', url: 'linkedin.com/in/marcusj' }],
    photo: 'https://randomuser.me/api/portraits/men/75.jpg',
    codeLanguage: 'go',
  },
  {
    personal: { firstName: 'Yuki', lastName: 'Tanaka', title: 'iOS Developer', email: 'yuki@apple.dev', phone: '+81 90 1234 5678', location: 'Tokyo, Japan', age: 26 },
    summary: 'Mobile developer focused on crafting delightful iOS experiences. SwiftUI enthusiast and open-source contributor.',
    skills: { platforms: ['iOS', 'macOS', 'watchOS', 'Xcode'], programmingLanguages: ['Swift', 'Objective-C', 'Kotlin', 'TypeScript'], software: ['Xcode', 'Figma', 'Firebase', 'CoreData'] },
    education: [{ id: '1', school: 'University of Tokyo', degree: 'Master', field: 'Human-Computer Interaction', startYear: 2019, endYear: 2021, description: 'Research on gesture-based mobile interfaces.' }],
    experience: [{ id: '1', company: 'LINE', role: 'Senior iOS Engineer', startDate: '04/2022', endDate: null, description: 'Leading iOS development for messaging app with 90M users.', technologies: ['Swift', 'SwiftUI', 'Combine'] }, { id: '2', company: 'Mercari', role: 'iOS Developer', startDate: '04/2021', endDate: '03/2022', description: 'Built marketplace features with clean architecture patterns.', technologies: ['Swift', 'RxSwift', 'MVVM'] }],
    languages: [{ name: 'Japanese', level: 'Native' }, { name: 'English', level: 'Advanced' }],
    personality: ['Creative', 'Perfectionist', 'User-Focused'],
    media: [{ platform: 'GitHub', url: 'github.com/yukitanaka' }, { platform: 'Portfolio', url: 'yuki.dev' }],
    photo: 'https://randomuser.me/api/portraits/men/18.jpg',
    codeLanguage: 'java',
  },
  {
    personal: { firstName: 'Elena', lastName: 'Petrova', title: 'Backend Engineer', email: 'elena@backend.dev', phone: '+7 999 123 4567', location: 'Berlin, Germany', age: 29 },
    summary: 'Backend engineer specializing in high-performance systems. Rust advocate building low-latency services.',
    skills: { platforms: ['Linux', 'Docker', 'AWS', 'Cloudflare'], programmingLanguages: ['Rust', 'Go', 'C++', 'Python'], software: ['PostgreSQL', 'Redis', 'RabbitMQ', 'Nginx'] },
    education: [{ id: '1', school: 'TU Berlin', degree: 'Master', field: 'Software Engineering', startYear: 2017, endYear: 2019, description: 'Thesis on memory-safe systems programming.' }],
    experience: [{ id: '1', company: 'Cloudflare', role: 'Systems Engineer', startDate: '08/2021', endDate: null, description: 'Building edge computing platform serving billions of requests.', technologies: ['Rust', 'C', 'Linux'] }, { id: '2', company: 'JetBrains', role: 'Software Developer', startDate: '01/2019', endDate: '07/2021', description: 'Worked on IDE performance and code analysis tools.', technologies: ['Kotlin', 'Rust', 'LLVM'] }],
    languages: [{ name: 'Russian', level: 'Native' }, { name: 'English', level: 'Fluent' }, { name: 'German', level: 'Advanced' }],
    personality: ['Precise', 'Performance-Driven', 'Thoughtful'],
    media: [{ platform: 'GitHub', url: 'github.com/elenapetrova' }, { platform: 'Blog', url: 'elena.codes' }],
    photo: 'https://randomuser.me/api/portraits/women/68.jpg',
    codeLanguage: 'rust',
  },
  {
    personal: { firstName: 'James', lastName: 'Wright', title: 'Security Engineer', email: 'james@sec.dev', phone: '+44 7700 900123', location: 'London, UK', age: 33 },
    summary: 'Cybersecurity professional with expertise in application security and penetration testing. OSCP certified.',
    skills: { platforms: ['Kali Linux', 'AWS', 'Azure', 'Docker'], programmingLanguages: ['Python', 'Go', 'C', 'Bash'], software: ['Burp Suite', 'Wireshark', 'Metasploit', 'Ghidra'] },
    education: [{ id: '1', school: 'Imperial College London', degree: 'Master', field: 'Information Security', startYear: 2013, endYear: 2015, description: 'Research on cryptographic protocol analysis.' }],
    experience: [{ id: '1', company: 'Google', role: 'Senior Security Engineer', startDate: '01/2022', endDate: null, description: 'Leading application security reviews for Cloud products.', technologies: ['Go', 'Python', 'GCP'] }, { id: '2', company: 'NCC Group', role: 'Security Consultant', startDate: '06/2016', endDate: '12/2021', description: 'Performed 100+ security assessments for Fortune 500 companies.', technologies: ['Python', 'C', 'Assembly'] }],
    languages: [{ name: 'English', level: 'Native' }, { name: 'French', level: 'Intermediate' }],
    personality: ['Analytical', 'Persistent', 'Ethical'],
    media: [{ platform: 'GitHub', url: 'github.com/jameswright' }, { platform: 'Twitter', url: 'twitter.com/jwrightsec' }],
    photo: 'https://randomuser.me/api/portraits/men/52.jpg',
    codeLanguage: 'python',
  },
  {
    personal: { firstName: 'Priya', lastName: 'Sharma', title: 'Frontend Developer', email: 'priya@ui.dev', phone: '+91 98765 43210', location: 'Bangalore, India', age: 27 },
    summary: 'Frontend developer passionate about accessible web experiences. React and design systems specialist.',
    skills: { platforms: ['Vercel', 'Netlify', 'Chromatic', 'Figma'], programmingLanguages: ['TypeScript', 'JavaScript', 'CSS', 'HTML'], software: ['Storybook', 'Playwright', 'Webpack', 'Vite'] },
    education: [{ id: '1', school: 'IIT Bangalore', degree: 'Bachelor', field: 'Computer Science', startYear: 2015, endYear: 2019, description: 'Graduated top of class with focus on HCI.' }],
    experience: [{ id: '1', company: 'Figma', role: 'Frontend Engineer', startDate: '06/2022', endDate: null, description: 'Building the design tool used by millions of designers worldwide.', technologies: ['TypeScript', 'React', 'WebGL'] }, { id: '2', company: 'Flipkart', role: 'UI Engineer', startDate: '07/2019', endDate: '05/2022', description: 'Led design system powering India\'s largest e-commerce platform.', technologies: ['React', 'TypeScript', 'Storybook'] }],
    languages: [{ name: 'Hindi', level: 'Native' }, { name: 'English', level: 'Fluent' }, { name: 'Kannada', level: 'Intermediate' }],
    personality: ['Creative', 'Empathetic', 'Detail Oriented'],
    media: [{ platform: 'GitHub', url: 'github.com/priyasharma' }, { platform: 'Dribbble', url: 'dribbble.com/priya' }],
    photo: 'https://randomuser.me/api/portraits/women/29.jpg',
    codeLanguage: 'typescript',
  },
  {
    personal: { firstName: 'Oscar', lastName: 'Mendez', title: 'Game Developer', email: 'oscar@gamedev.io', phone: '+34 612 345 678', location: 'Barcelona, Spain', age: 30 },
    summary: 'Game developer with experience shipping AAA and indie titles. Specialized in graphics programming and physics engines.',
    skills: { platforms: ['Unity', 'Unreal Engine', 'Steam', 'PlayStation'], programmingLanguages: ['C++', 'C#', 'Rust', 'HLSL'], software: ['Blender', 'Maya', 'Perforce', 'RenderDoc'] },
    education: [{ id: '1', school: 'Universitat Pompeu Fabra', degree: 'Master', field: 'Game Development', startYear: 2016, endYear: 2018, description: 'Thesis on real-time global illumination techniques.' }],
    experience: [{ id: '1', company: 'Ubisoft', role: 'Senior Graphics Programmer', startDate: '09/2020', endDate: null, description: 'Working on rendering pipeline for open-world games.', technologies: ['C++', 'Vulkan', 'HLSL'] }, { id: '2', company: 'Indie Studio', role: 'Lead Developer', startDate: '01/2018', endDate: '08/2020', description: 'Shipped award-winning puzzle game on Steam and consoles.', technologies: ['Unity', 'C#', 'Shader Graph'] }],
    languages: [{ name: 'Spanish', level: 'Native' }, { name: 'English', level: 'Fluent' }, { name: 'Catalan', level: 'Native' }],
    personality: ['Creative', 'Passionate', 'Collaborative'],
    media: [{ platform: 'GitHub', url: 'github.com/oscarmendez' }, { platform: 'Portfolio', url: 'oscar.games' }],
    photo: 'https://randomuser.me/api/portraits/men/45.jpg',
    codeLanguage: 'csharp',
  },
  {
    personal: { firstName: 'Amara', lastName: 'Obi', title: 'Cloud Architect', email: 'amara@cloud.dev', phone: '+234 801 234 5678', location: 'Lagos, Nigeria', age: 35 },
    summary: 'Cloud architect designing resilient distributed systems. AWS Solutions Architect Professional certified.',
    skills: { platforms: ['AWS', 'Azure', 'GCP', 'Kubernetes'], programmingLanguages: ['Go', 'Python', 'TypeScript', 'Java'], software: ['Terraform', 'CDK', 'Pulumi', 'Datadog'] },
    education: [{ id: '1', school: 'University of Lagos', degree: 'Bachelor', field: 'Computer Science', startYear: 2009, endYear: 2013, description: 'First class honors with focus on distributed computing.' }],
    experience: [{ id: '1', company: 'AWS', role: 'Principal Solutions Architect', startDate: '03/2021', endDate: null, description: 'Designing cloud architectures for enterprise customers across Africa.', technologies: ['AWS', 'Go', 'Terraform'] }, { id: '2', company: 'Andela', role: 'Senior Engineer', startDate: '01/2017', endDate: '02/2021', description: 'Built scalable microservices platform for developer talent marketplace.', technologies: ['Node.js', 'Python', 'Kubernetes'] }],
    languages: [{ name: 'English', level: 'Native' }, { name: 'Igbo', level: 'Native' }, { name: 'Yoruba', level: 'Conversational' }],
    personality: ['Strategic', 'Mentor', 'Big-Picture Thinker'],
    media: [{ platform: 'GitHub', url: 'github.com/amaraobi' }, { platform: 'LinkedIn', url: 'linkedin.com/in/amaraobi' }],
    photo: 'https://randomuser.me/api/portraits/women/56.jpg',
    codeLanguage: 'go',
  },
  {
    personal: { firstName: 'Lina', lastName: 'Berg', title: 'Embedded Developer', email: 'lina@embedded.dev', phone: '+46 70 123 4567', location: 'Stockholm, Sweden', age: 32 },
    summary: 'Embedded systems engineer building firmware for IoT and robotics. Passionate about Rust for safety-critical systems.',
    skills: { platforms: ['ARM Cortex', 'RISC-V', 'FreeRTOS', 'Zephyr'], programmingLanguages: ['Rust', 'C', 'C++', 'Python'], software: ['GDB', 'Oscilloscope', 'KiCad', 'JTAG'] },
    education: [{ id: '1', school: 'KTH Royal Institute', degree: 'Master', field: 'Embedded Systems', startYear: 2014, endYear: 2016, description: 'Thesis on real-time operating systems for autonomous drones.' }],
    experience: [{ id: '1', company: 'Spotify', role: 'Embedded Engineer', startDate: '01/2022', endDate: null, description: 'Building firmware for next-gen hardware audio devices.', technologies: ['Rust', 'C', 'Bluetooth LE'] }, { id: '2', company: 'ABB Robotics', role: 'Firmware Developer', startDate: '09/2016', endDate: '12/2021', description: 'Developed motor control firmware for industrial robots.', technologies: ['C', 'C++', 'FreeRTOS'] }],
    languages: [{ name: 'Swedish', level: 'Native' }, { name: 'English', level: 'Fluent' }, { name: 'Norwegian', level: 'Conversational' }],
    personality: ['Precise', 'Patient', 'Hardware-Minded'],
    media: [{ platform: 'GitHub', url: 'github.com/linaberg' }, { platform: 'Blog', url: 'lina.embedded.dev' }],
    photo: 'https://randomuser.me/api/portraits/women/82.jpg',
    codeLanguage: 'rust',
  },
];
